# Generated by Django 5.1.5 on 2025-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_customuser_wallet_balance_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
