# Generated by Django 5.1.6 on 2025-02-07 23:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expiry),
        ),
    ]
